services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    container_name: appservice
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      APP_ENV: local
      CONTAINER_ROLE: app
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    working_dir: /var/www
    volumes:
      - ./php/local.ini:/usr/local/etc/conf.d/local.ini
      - ./appservice:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: appserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./appservice:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: app-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.44
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: spreadsheet
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app@2024
      MYSQL_ROOT_PASSWORD: app_database
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  redis:
    driver: local
  es_data:
    driver: local
