monolog:
  handlers:
    main:
      type: rotating_file
      path: '%kernel.logs_dir%/app.log'
      level: debug
      max_files: 30
      channels: ["!event", "!console"]

    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]